{% set name = "cosmopower" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cosmopower-{{ version }}.tar.gz
  sha256: 650e87bc9a5a754a9bb60facd0fa44ae1a3cc4d4e20548cb924c2b38bee8704a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - tensorflow <2.14
    - scikit-learn
    - tqdm
    - pytest
    - tensorflow-probability <0.22

test:
  imports:
    - cosmopower
  commands:
    - pip check
  requires:
    - python >={{ python_min }}
    - pip

about:
  home: https://github.com/alessiospuriomancini/cosmopower
  summary: Machine Learning - accelerated Bayesian inference
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - joezuntz
    - alessiospuriomancini
